# Generated by Django 5.0.2 on 2026-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('receptionist', 'Recipient (Legacy)'), ('viewer', 'Donor (Legacy)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('receptionist', 'Recipient (Legacy)'), ('viewer', 'Donor (Legacy)')], max_length=50),
        ),
    ]
