# Generated by Django 5.0.2 on 2026-06-10

import accounts.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_rolepermission_role_name_alter_user_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.image_path.user_avatar_upload_path,
            ),
        ),
    ]
