# Generated by Django 6.0.1 on 2026-03-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_seed_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportexportjob',
            new_name='report_expo_owner_i_fba4fc_idx',
            old_name='report_expo_owner_i_ce7d7b_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexportjob',
            new_name='report_expo_status_3befab_idx',
            old_name='report_expo_status__1b8e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexportjob',
            new_name='report_expo_report__33a571_idx',
            old_name='report_expo_report__4fcd69_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexportjob',
            new_name='report_expo_expires_d02a7d_idx',
            old_name='report_expo_expires_8f66af_idx',
        ),
    ]
