# Generated by Django 6.0.1 on 2026-03-02 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0002_seed_permissions'),
        ('donations', '0003_backfill_from_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_type', models.CharField(max_length=50)),
                ('event_key', models.CharField(choices=[('blood_request_created', 'Blood Request Created'), ('blood_request_verified', 'Blood Request Verified'), ('blood_request_assigned', 'Blood Request Assigned'), ('blood_request_completed', 'Blood Request Completed'), ('blood_request_cancelled', 'Blood Request Cancelled'), ('donation_status_updated', 'Donation Status Updated'), ('donation_primary_changed', 'Donation Primary Changed'), ('donation_reminder', 'Donation Reminder'), ('account_locked', 'Account Locked'), ('password_reset_code_sent', 'Password Reset Code Sent'), ('email_verified', 'Email Verified'), ('system_alert', 'System Alert')], max_length=100)),
                ('type', models.CharField(choices=[('request_update', 'Request Update'), ('donation_update', 'Donation Update'), ('auth', 'Authentication'), ('system', 'System'), ('reminder', 'Reminder')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_via', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=191, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='donations.donation')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='blood_requests.bloodrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx'), models.Index(fields=['sent_via'], name='notificatio_sent_vi_615c3e_idx'), models.Index(fields=['hidden_at'], name='notificatio_hidden__abc1ff_idx'), models.Index(fields=['event_key'], name='notificatio_event_k_7ca818_idx'), models.Index(fields=['dedupe_key'], name='notificatio_dedupe__69737b_idx'), models.Index(fields=['request'], name='notificatio_request_d19539_idx'), models.Index(fields=['donation'], name='notificatio_donatio_b132e8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('hidden_at__isnull', True), ('dedupe_key__isnull', False), models.Q(('dedupe_key', ''), _negated=True)), fields=('user', 'sent_via', 'dedupe_key'), name='uniq_notification_dedupe_user_channel_active')],
            },
        ),
    ]
