from io import BytesIO
from html import escape

from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from reports.services import (
    build_donation_analytics,
    build_emergency_analysis,
    build_geographic_distance,
    build_hospital_performance,
    build_request_analytics,
    build_system_performance,
)


def _format_value(value):
    if value is None:
        return "N/A"
    if isinstance(value, float):
        return f"{value:.2f}".rstrip("0").rstrip(".")
    if isinstance(value, dict):
        return ", ".join(f"{key}: {_format_value(item)}" for key, item in value.items()) or "None"
    return str(value)


def _humanize_key(value):
    return str(value).replace("_", " ").title()


def _summary_rows(summary):
    return [[_humanize_key(key), _format_value(value)] for key, value in summary.items()]


def _table(rows, column_widths=None):
    table = Table(rows, colWidths=column_widths, hAlign="LEFT", repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5e1")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return table


def _paragraph(styles, text, style="BodyText"):
    return Paragraph(escape(str(text)), styles[style])


def _add_section(story, styles, title, summary):
    story.append(_paragraph(styles, title, "Heading2"))
    story.append(_table([["Metric", "Value"], *_summary_rows(summary)], [2.4 * inch, 3.8 * inch]))
    story.append(Spacer(1, 0.16 * inch))


def _add_rows(story, styles, title, headers, rows, mapper, limit=5):
    if not rows:
        return
    story.append(_paragraph(styles, title, "Heading3"))
    mapped_rows = [mapper(row) for row in rows[:limit]]
    story.append(_table([headers, *mapped_rows]))
    story.append(Spacer(1, 0.14 * inch))


def build_management_summary_pdf(filters, user):
    generated_at = timezone.localtime()
    report_payloads = {
        "Request Analytics": build_request_analytics(filters),
        "Donation Analytics": build_donation_analytics(filters),
        "Hospital Performance": build_hospital_performance(filters),
        "Emergency Analysis": build_emergency_analysis(filters),
        "Geographic Distance": build_geographic_distance(filters),
        "System Performance": build_system_performance(filters),
    }

    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
        title="Blood Donation Management Report",
    )
    styles = getSampleStyleSheet()
    story = [
        _paragraph(styles, "Blood Donation Management Report", "Title"),
        Spacer(1, 0.12 * inch),
        _paragraph(styles, f"Generated at: {generated_at.strftime('%Y-%m-%d %H:%M')}", "BodyText"),
        _paragraph(styles, f"Generated by: {getattr(user, 'username', 'admin')}", "BodyText"),
        _paragraph(
            styles,
            "Date range: "
            f"{timezone.localtime(filters['date_from']).strftime('%Y-%m-%d')} to "
            f"{timezone.localtime(filters['date_to']).strftime('%Y-%m-%d')}",
            "BodyText",
        ),
        Spacer(1, 0.2 * inch),
    ]

    for title, payload in report_payloads.items():
        _add_section(story, styles, title, payload.get("summary", {}))

        if title == "Request Analytics":
            blood_groups = payload.get("breakdowns", {}).get("blood_group", [])
            _add_rows(
                story,
                styles,
                "Blood Group Breakdown",
                ["Blood Group", "Count"],
                blood_groups,
                lambda row: [_format_value(row.get("blood_group")), _format_value(row.get("count"))],
            )

        if title == "Donation Analytics":
            distance_buckets = payload.get("distributions", {}).get("distance_buckets", [])
            _add_rows(
                story,
                styles,
                "Donation Distance Buckets",
                ["Distance", "Count", "Percent"],
                distance_buckets,
                lambda row: [
                    _format_value(row.get("label")),
                    _format_value(row.get("count")),
                    f"{_format_value(row.get('percentage'))}%",
                ],
            )

        if title == "Hospital Performance":
            rows = sorted(payload.get("rows", []), key=lambda item: item.get("request_volume", 0), reverse=True)
            _add_rows(
                story,
                styles,
                "Top Hospitals",
                ["Hospital", "City", "Requests", "Completion"],
                rows,
                lambda row: [
                    _format_value(row.get("hospital_name")),
                    _format_value(row.get("city")),
                    _format_value(row.get("request_volume")),
                    f"{_format_value(row.get('completion_rate'))}%",
                ],
            )

        if title == "Geographic Distance":
            city_rows = payload.get("city_distribution", [])
            _add_rows(
                story,
                styles,
                "Request Cities",
                ["City", "Count"],
                city_rows,
                lambda row: [_format_value(row.get("city")), _format_value(row.get("count"))],
            )

        if title == "System Performance":
            data_quality = payload.get("data_quality", {})
            if data_quality:
                story.append(_paragraph(styles, "Data Quality", "Heading3"))
                story.append(_table([["Metric", "Value"], *_summary_rows(data_quality)], [2.4 * inch, 3.8 * inch]))
                story.append(Spacer(1, 0.14 * inch))

    document.build(story)
    return buffer.getvalue()
