# Generated by Django 6.0.1 on 2026-03-12 08:33

import donors.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=donors.image_path.donor_profile_picture_upload_path)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donors',
                'indexes': [models.Index(fields=['status'], name='donors_status_8b8b56_idx'), models.Index(fields=['blood_group'], name='donors_blood_g_d4753e_idx'), models.Index(fields=['last_name'], name='donors_last_na_62d3b2_idx'), models.Index(fields=['phone'], name='donors_phone_1921a8_idx'), models.Index(fields=['emergency_contact_phone'], name='donors_emergency_phone_idx'), models.Index(fields=['latitude'], name='donors_latitud_86ae1d_idx'), models.Index(fields=['longitude'], name='donors_longitu_228e1b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('phone',), name='uniq_donors_phone_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_donors_email_active')],
            },
        ),
    ]
