# Generated by Django 5.0.2 on 2026-04-20 10:06

from django.db import migrations, models


def drop_stale_emergency_phone_index(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = 'donors'
              AND index_name = 'donors_emergency_phone_idx'
            """
        )
        has_index = cursor.fetchone()[0] > 0

    if has_index:
        schema_editor.execute(
            "ALTER TABLE `donors` DROP INDEX `donors_emergency_phone_idx`"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_update_donor_fields'),
    ]

    operations = [
        migrations.RunPython(drop_stale_emergency_phone_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['age'], name='donors_age_f98a08_idx'),
        ),
    ]
