# Generated by Django 5.0.2 on 2026-02-22

from django.db import migrations, models
from django.db.models import Q
import donors.image_path


class Migration(migrations.Migration):
    dependencies = [
        ("donors", "0002_seed_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=donors.image_path.donor_profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name="donor",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("blocked", "Blocked"), ("pending", "Pending")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(fields=["emergency_contact_phone"], name="donors_emergency_phone_idx"),
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.UniqueConstraint(
                condition=Q(deleted_at__isnull=True),
                fields=("phone",),
                name="uniq_donors_phone_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.UniqueConstraint(
                condition=Q(deleted_at__isnull=True, email__isnull=False) & ~Q(email=""),
                fields=("email",),
                name="uniq_donors_email_active",
            ),
        ),
    ]
