# Generated by Django 6.0.1 on 2026-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donor_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['latitude'], name='donors_latitud_86ae1d_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['longitude'], name='donors_longitu_228e1b_idx'),
        ),
    ]
