# Generated by Django 5.0.2 on 2026-04-30 11:40

from django.db import migrations


def backfill_donor_user_links(apps, schema_editor):
    Donor = apps.get_model("donors", "Donor")
    User = apps.get_model("accounts", "User")

    donors = Donor.objects.filter(user__isnull=True, deleted_at__isnull=True)
    for donor in donors.iterator():
        matched_user = (
            User.objects.filter(
                deleted_at__isnull=True,
                is_active=True,
                role_name__in=["donor", "viewer"],
                phone=donor.phone,
            )
            .order_by("id")
            .first()
        )
        if not matched_user and donor.email:
            matched_user = (
                User.objects.filter(
                    deleted_at__isnull=True,
                    is_active=True,
                    role_name__in=["donor", "viewer"],
                    email__iexact=donor.email,
                )
                .order_by("id")
                .first()
            )
        if not matched_user:
            continue
        if Donor.objects.filter(user_id=matched_user.id).exists():
            continue
        donor.user_id = matched_user.id
        donor.save(update_fields=["user"])


def reverse_backfill_donor_user_links(apps, schema_editor):
    Donor = apps.get_model("donors", "Donor")
    Donor.objects.update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0004_donor_user"),
    ]

    operations = [
        migrations.RunPython(backfill_donor_user_links, reverse_backfill_donor_user_links),
    ]
