# Generated by Django 5.0.2 on 2026-05-01 11:20

from django.db import migrations, models


def backfill_donor_status_to_active(apps, schema_editor):
    Donor = apps.get_model("donors", "Donor")
    Donor._base_manager.all().update(status="active")


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0005_backfill_donor_user_links"),
    ]

    operations = [
        migrations.RunPython(backfill_donor_status_to_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="donor",
            name="status",
            field=models.CharField(
                choices=[("active", "Active")],
                default="active",
                max_length=20,
            ),
        ),
    ]
