# Generated by Django 5.0.2 on 2026-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_backfill_donor_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='local_address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='permanent_address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
