# Generated by Django 5.0.2 on 2026-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_donor_local_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='local_address',
        ),
        migrations.AlterField(
            model_name='donor',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
