# Generated by Django 5.0.2 on 2026-05-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_remove_donor_local_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='permanent_address',
        ),
    ]
