# Generated by Django 5.0.2 on 2026-05-01 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_remove_donor_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
