# Generated by Django 6.0.1 on 2026-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hospitals',
                'indexes': [models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'), models.Index(fields=['city'], name='hospitals_city_7ae4d2_idx'), models.Index(fields=['phone'], name='hospitals_phone_615604_idx'), models.Index(fields=['email'], name='hospitals_email_248167_idx'), models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'city'), name='uniq_hospitals_name_city_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='uniq_hospitals_phone_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_hospitals_email_active')],
            },
        ),
    ]
