# Generated by Django 5.0.2 on 2026-02-26

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Hospital",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                        ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                        ("name", models.CharField(max_length=200)),
                        ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                        ("address", models.TextField(blank=True, null=True)),
                        ("city", models.CharField(max_length=100)),
                        ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                        ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                    ],
                    options={
                        "db_table": "hospitals",
                        "indexes": [
                            models.Index(fields=["name"], name="hospitals_name_9e93ed_idx"),
                            models.Index(fields=["city"], name="hospitals_city_7ae4d2_idx"),
                            models.Index(fields=["contact_phone"], name="hospitals_contact_121925_idx"),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                condition=Q(deleted_at__isnull=True),
                                fields=("name", "city"),
                                name="uniq_hospitals_name_city_active",
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]

