# Generated by Django 5.0.2 on 2026-02-26

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0001_initial"),
        ("recipients", "0002_seed_permissions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hospital",
            name="hospitals_contact_121925_idx",
        ),
        migrations.RenameField(
            model_name="hospital",
            old_name="contact_phone",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="hospital",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="hospital",
            constraint=models.UniqueConstraint(
                condition=Q(deleted_at__isnull=True, phone__isnull=False) & ~Q(phone=""),
                fields=("phone",),
                name="uniq_hospitals_phone_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="hospital",
            constraint=models.UniqueConstraint(
                condition=Q(deleted_at__isnull=True, email__isnull=False) & ~Q(email=""),
                fields=("email",),
                name="uniq_hospitals_email_active",
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["phone"], name="hospitals_phone_615604_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["email"], name="hospitals_email_248167_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["is_active"], name="hospitals_is_acti_ff4c80_idx"),
        ),
    ]
