# Generated by Django 5.0.2 on 2026-04-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_add_province'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hospital',
            new_name='hospitals_provinc_516dff_idx',
            old_name='hospitals_province_0f6c85_idx',
        ),
    ]
