# Generated by Django 6.0.1 on 2026-03-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0002_seed_permissions'),
        ('donors', '0004_donor_latitude_donor_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('response_time', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_arrival_time', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='blood_requests.bloodrequest')),
            ],
            options={
                'db_table': 'donations',
                'indexes': [models.Index(fields=['request'], name='donations_request_1ae951_idx'), models.Index(fields=['donor'], name='donations_donor_i_e43edd_idx'), models.Index(fields=['status'], name='donations_status_14f677_idx'), models.Index(fields=['is_primary'], name='donations_is_prim_e2e60b_idx'), models.Index(fields=['notified_at'], name='donations_notifie_eeaf9c_idx'), models.Index(fields=['priority_score'], name='donations_priorit_180615_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('request', 'donor'), name='uniq_donation_request_donor_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True), ('status__in', ('pending', 'accepted', 'en_route', 'arrived'))), fields=('request',), name='uniq_primary_donation_request_active')],
            },
        ),
    ]
