# Generated by Django 5.0.2 on 2026-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0004_remove_bloodrequest_priority'),
        ('donations', '0001_initial'),
        ('donors', '0010_alter_donor_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donation',
            name='uniq_primary_donation_request_active',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_priorit_180615_idx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='priority_score',
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True), ('status__in', ('pending', 'accepted'))), fields=('request',), name='uniq_primary_donation_request_active'),
        ),
    ]
