# Generated by Django 6.0.1 on 2026-03-07 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('section', models.CharField(choices=[('general', 'general'), ('user_roles', 'user_roles'), ('notifications', 'notifications'), ('emergency_alerts', 'emergency_alerts'), ('blood_request_rules', 'blood_request_rules'), ('donor_eligibility', 'donor_eligibility'), ('auto_matching', 'auto_matching'), ('localization', 'localization'), ('security', 'security')], max_length=64)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reset_to_default', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['section', 'created_at'], name='system_sett_section_c11a39_idx'), models.Index(fields=['changed_by', 'created_at'], name='system_sett_changed_b90785_idx')],
            },
        ),
    ]
