# Generated by Django 6.0.1 on 2026-02-28 07:15

import blood_requests.image_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0004_donor_latitude_donor_longitude_and_more'),
        ('hospitals', '0003_seed_permissions'),
        ('recipients', '0003_migrate_hospital_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_needed', models.PositiveSmallIntegerField()),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('estimated_time_to_fulfill', models.PositiveIntegerField(blank=True, null=True)),
                ('nearby_donors_count', models.PositiveIntegerField(default=0)),
                ('total_notified_donors', models.PositiveIntegerField(default=0)),
                ('auto_match_enabled', models.BooleanField(default=True)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('admin', 'Admin'), ('recipient', 'Recipient')], max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to=blood_requests.image_path.blood_request_medical_report_upload_path)),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to=blood_requests.image_path.blood_request_prescription_image_upload_path)),
                ('emergency_proof', models.FileField(blank=True, null=True, upload_to=blood_requests.image_path.blood_request_emergency_proof_upload_path)),
                ('assigned_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_blood_requests', to='donors.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_requests', to='hospitals.hospital')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_requests', to='recipients.recipient')),
            ],
            options={
                'db_table': 'blood_requests',
            },
        ),
        migrations.CreateModel(
            name='BloodRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('sms', 'SMS'), ('email', 'Email')], default='in_app', max_length=20)),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_request_notifications', to='donors.donor')),
            ],
            options={
                'db_table': 'blood_request_notifications',
            },
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status'], name='blood_reque_status_bd26a1_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group'], name='blood_reque_blood_g_72a8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['priority'], name='blood_reque_priorit_6b1810_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['request_type'], name='blood_reque_request_5e30ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['response_deadline'], name='blood_reque_respons_dc6085_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['is_active'], name='blood_reque_is_acti_c867c9_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['is_emergency'], name='blood_reque_is_emer_f05091_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['hospital'], name='blood_reque_hospita_77128a_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['recipient'], name='blood_reque_recipie_859e71_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['assigned_donor'], name='blood_reque_assigne_0a3aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', 'is_active', 'response_deadline'], name='blood_req_stat_dead_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(('units_needed__gte', 1)), name='blood_request_units_min_one'),
        ),
        migrations.AddIndex(
            model_name='bloodrequestnotification',
            index=models.Index(fields=['blood_request'], name='blood_reque_blood_r_eb7a14_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequestnotification',
            index=models.Index(fields=['donor'], name='blood_reque_donor_i_286fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequestnotification',
            index=models.Index(fields=['channel'], name='blood_reque_channel_6f6f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequestnotification',
            index=models.Index(fields=['delivery_status'], name='blood_reque_deliver_120fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequestnotification',
            index=models.Index(fields=['response_status'], name='blood_reque_respons_230072_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequestnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('blood_request', 'donor', 'channel'), name='uniq_blood_request_donor_channel_active'),
        ),
    ]
