# Generated by Django 6.0.1 on 2026-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(('units_needed__gte', 1)), name='blood_request_units_min_one'),
        ),
    ]
