# Generated by Django 5.0.2 on 2026-05-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_bloodrequest_blood_request_units_min_one'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bloodrequest',
            name='blood_request_units_min_one_v2',
        ),
    ]
