# Generated by Django 6.0.1 on 2026-03-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_bloodrequest_blood_request_units_min_one'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bloodrequest',
            name='blood_request_units_min_one',
        ),
    ]
