# Generated by Django 5.0.2 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                "db_table": "hospitals",
                "indexes": [
                    models.Index(fields=["name"], name="hospitals_name_9e93ed_idx"),
                    models.Index(fields=["city"], name="hospitals_city_7ae4d2_idx"),
                    models.Index(fields=["contact_phone"], name="hospitals_contact_121925_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(deleted_at__isnull=True),
                        fields=("name", "city"),
                        name="uniq_hospitals_name_city_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "required_blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("age", models.PositiveSmallIntegerField()),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female"), ("other", "Other")], max_length=10)),
                (
                    "emergency_level",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent"), ("critical", "Critical")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("active", "Active"), ("blocked", "Blocked")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipients",
                        to="recipients.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "recipients",
                "indexes": [
                    models.Index(fields=["status"], name="recipients_status_6aa2a4_idx"),
                    models.Index(fields=["required_blood_group"], name="recipients_require_bf89dc_idx"),
                    models.Index(fields=["emergency_level"], name="recipients_emergen_b39769_idx"),
                    models.Index(fields=["full_name"], name="recipients_full_na_7e38e1_idx"),
                    models.Index(fields=["phone"], name="recipients_phone_d259d3_idx"),
                    models.Index(fields=["hospital"], name="recipients_hospita_baddb4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(deleted_at__isnull=True),
                        fields=("phone",),
                        name="uniq_recipients_phone_active",
                    ),
                    models.UniqueConstraint(
                        condition=Q(deleted_at__isnull=True, email__isnull=False) & ~Q(email=""),
                        fields=("email",),
                        name="uniq_recipients_email_active",
                    ),
                ],
            },
        ),
    ]
