# Generated by Django 6.0.1 on 2026-03-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('required_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('emergency_level', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'recipients',
                'indexes': [models.Index(fields=['status'], name='recipients_status_6aa2a4_idx'), models.Index(fields=['required_blood_group'], name='recipients_require_bf89dc_idx'), models.Index(fields=['emergency_level'], name='recipients_emergen_b39769_idx'), models.Index(fields=['full_name'], name='recipients_full_na_7e38e1_idx'), models.Index(fields=['phone'], name='recipients_phone_d259d3_idx'), models.Index(fields=['hospital'], name='recipients_hospita_baddb4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('phone',), name='uniq_recipients_phone_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_recipients_email_active')],
            },
        ),
    ]
