# Generated by Django 5.0.2 on 2026-02-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0002_hospital_schema_updates"),
        ("recipients", "0002_seed_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipients",
                to="hospitals.hospital",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Hospital"),
            ],
        ),
    ]

