# Generated by Django 5.0.2 on 2026-04-30 11:40

from django.db import migrations


def backfill_recipient_user_links(apps, schema_editor):
    Recipient = apps.get_model("recipients", "Recipient")
    User = apps.get_model("accounts", "User")

    recipients = Recipient.objects.filter(user__isnull=True, deleted_at__isnull=True)
    for recipient in recipients.iterator():
        matched_user = (
            User.objects.filter(
                deleted_at__isnull=True,
                is_active=True,
                role_name__in=["recipient", "receptionist"],
                phone=recipient.phone,
            )
            .order_by("id")
            .first()
        )
        if not matched_user and recipient.email:
            matched_user = (
                User.objects.filter(
                    deleted_at__isnull=True,
                    is_active=True,
                    role_name__in=["recipient", "receptionist"],
                    email__iexact=recipient.email,
                )
                .order_by("id")
                .first()
            )
        if not matched_user:
            continue
        if Recipient.objects.filter(user_id=matched_user.id).exists():
            continue
        recipient.user_id = matched_user.id
        recipient.save(update_fields=["user"])


def reverse_backfill_recipient_user_links(apps, schema_editor):
    Recipient = apps.get_model("recipients", "Recipient")
    Recipient.objects.update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0004_recipient_user_alter_recipient_hospital"),
    ]

    operations = [
        migrations.RunPython(backfill_recipient_user_links, reverse_backfill_recipient_user_links),
    ]
