# Generated by Django 5.0.2 on 2026-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0005_backfill_recipient_user_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='required_blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
