# Generated by Django 6.0.1 on 2026-03-12 07:51

import core.image_path
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('users', 'Users'), ('reports', 'Reports'), ('settings', 'Settings'), ('donors', 'Donors'), ('recipients', 'Recipients'), ('hospitals', 'Hospitals'), ('blood_requests', 'Blood Requests'), ('donations', 'Donations'), ('notifications', 'Notifications')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['module'], name='permissions_module_2c0512_idx')],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_image', models.ImageField(blank=True, null=True, upload_to=core.image_path.settings_image_upload_path)),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('image', 'Image')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('notifications', 'Notifications'), ('integration', 'Integration'), ('billing', 'Billing')], default='general', max_length=20)),
            ],
            options={
                'db_table': 'settings',
                'indexes': [models.Index(fields=['setting_key'], name='settings_setting_a14441_idx')],
                'unique_together': {('setting_key',)},
            },
        ),
        migrations.CreateModel(
            name='SettingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_audit_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['section', 'changed_at'], name='setting_aud_section_673646_idx'), models.Index(fields=['changed_by', 'changed_at'], name='setting_aud_changed_26b57f_idx')],
            },
        ),
    ]
