# Generated by Django 6.0.1 on 2026-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('reports', 'Reports'), ('settings', 'Settings'), ('donors', 'Donors')], max_length=50),
        ),
    ]
