# Generated by Django 5.0.2 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_permission_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("users", "Users"),
                    ("reports", "Reports"),
                    ("settings", "Settings"),
                    ("donors", "Donors"),
                    ("recipients", "Recipients"),
                ],
                max_length=50,
            ),
        ),
    ]

