# Generated by Django 5.0.2 on 2026-06-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backuprecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backup_reco_backup__3db6eb_idx',
            old_name='backup_reco_backup__6faad6_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backup_reco_status_cd39ed_idx',
            old_name='backup_reco_status_8447a1_idx',
        ),
    ]
