# Generated by Django 6.0.1 on 2026-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('reports', 'Reports'), ('settings', 'Settings'), ('donors', 'Donors'), ('recipients', 'Recipients'), ('hospitals', 'Hospitals'), ('blood_requests', 'Blood Requests')], max_length=50),
        ),
    ]
