# Generated by Django 5.0.2 on 2026-03-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_permission_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(db_index=True, max_length=100)),
                ("old_value", models.JSONField(default=dict)),
                ("new_value", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setting_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "setting_audit_logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="settingauditlog",
            index=models.Index(fields=["section", "changed_at"], name="setting_aud_section_8906ea_idx"),
        ),
        migrations.AddIndex(
            model_name="settingauditlog",
            index=models.Index(fields=["changed_by", "changed_at"], name="setting_aud_changed_c3493f_idx"),
        ),
    ]
