# Generated by Django 6.0.1 on 2026-03-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_settings_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settingauditlog',
            new_name='setting_aud_section_673646_idx',
            old_name='setting_aud_section_8906ea_idx',
        ),
        migrations.RenameIndex(
            model_name='settingauditlog',
            new_name='setting_aud_changed_26b57f_idx',
            old_name='setting_aud_changed_c3493f_idx',
        ),
    ]
